// Auto-generated by @fern-api/cli-generator's copySpecs step.
// Edit the SDK template / generator if you need to change the shape.

mod custom;
mod sdk;

use fern_cli_sdk::app::CliApp;
use fern_cli_sdk::openapi::OpenApiBinding;
use fern_cli_sdk::auth::{PkceLoginFlow};

fn main() {
    let app = CliApp::new("elevenlabs")
        .login_flow(PkceLoginFlow::new("OAuth").client_id("c9c18126-5718-406a-8a12-21b69e5a888d").authorization_url("https://elevenlabs.io/app/oauth/authorize").token_url("https://api.us.elevenlabs.io/v1/oauth/token").scopes(["text_to_speech", "speech_to_speech", "speech_to_text", "sound_generation", "audio_isolation", "voice_generation", "forced_alignment", "music_generation", "image_video_generation", "flows", "models_read", "voices_read", "voices_write", "speech_history_read", "speech_history_write", "dubbing_read", "dubbing_write", "pronunciation_dictionaries_read", "pronunciation_dictionaries_write", "projects_read", "projects_write", "convai_read", "convai_write", "add_voice_from_voice_library", "create_instant_voice_clone", "create_professional_voice_clone", "user_read", "workspace_read"]).redirect_host("localhost").redirect_ports([8484, 8483, 8482]))
        .binding(
            OpenApiBinding::new()
                .spec(include_str!("openapi0.json"))
        );

    let app = custom::register(app);

    app.run()
}
